---
name: Apply terraform code

on:
  # Exposes a 'run now' hook
  workflow_dispatch:
jobs:
  # Note: jobs are not guaranteed to execute in order unless constrained to do so
  apply_terraform: # should be a meaningful name
    runs-on: ubuntu-latest # github.com runners.
    # Environments are not required for this workflow, however, are used for future proofing
    environment: demo
    # Env exposes environmental variables, such as secrets, to each of the steps below. This can be set for all steps here, or within each step.

    env:
      # access keys for cloudian required 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      TF_VAR_user: ${{ secrets.VCD_USER }}
      TF_VAR_password: ${{ secrets.VCD_PASSWORD }}
      
      TF_VAR_win_password: ${{ secrets.WIN_PASSWORD }}
      TF_VAR_linux_user: ${{ secrets.LINUX_USER }}
      TF_VAR_linux_password_cleartext: ${{ secrets.LINUX_PASSWORD }}

    steps:
      # Checks out your code
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.3.6"

      - uses: actions/setup-go@v2
        with:
          go-version: "1.19.5"
      
      - uses: actions/setup-node@v3  
        with:
          node-version: 16
      - name: Terraform Init
        run: terraform init -backend-config=backend.hcl

      - name: Terraform apply
        run: terraform apply -auto-approve
          